# Generated by Django 4.2 on 2023-05-11 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='total_companies_bought',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='panel.team'),
        ),
    ]
